baseurl = "/"
languageCode = "en-us"
title = "Matt Freitas - Developer Journey"
theme = "nofancy"

#if not set copyright, default copyright template will be applied
copyright = "Copyright (c) 2017, Matt Freitas; all rights reserved."

[params]
    highlight="Assign a syntax highlight style"

[author]
    name = "Matt Freitas"
    github = "chupacabreh"
    linkedin = "matthew-freitas-547b48132"
    facebook = "matthew.freitas"
    gaID = "YOUR Google Analytics Tracking ID"
    twitter = "chupacabreh"
